import type { Complaint } from "./kanban-types";

/**
 * Fallback mock complaints used when Supabase is unreachable.
 * Each entry mirrors the shape returned by the `complaints` table.
 */
export const mockComplaints: Complaint[] = [
  {
    id: "d1e2f3a4-b5c6-7890-abcd-111111111111",
    ticket_id: "D1E2F3A4",
    title: "Garbage overflowing in bins in Kirti Nagar",
    description: "Multiple garbage bins in Kirti Nagar main market area are overflowing for the past 3 days. Foul smell is causing health concerns for nearby residents.",
    status: "submitted",
    severity: "L3",
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    address_text: "Main Market, Kirti Nagar, New Delhi",
    ward_name: "Kirti Nagar",
    assigned_department: null,
    assigned_officer_id: null,
    resolved_at: null,
    resolution_note: null,
  },
  {
    id: "e2f3g4a5-b6c7-8901-bcde-222222222222",
    ticket_id: "E2F3G4A5",
    title: "Potholes on Saket roads causing danger and inconvenience",
    description: "Deep potholes on the main road near Saket Metro Station. Multiple accidents reported. Urgently needs PWD attention.",
    status: "assigned",
    severity: "L2",
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    address_text: "Near Saket Metro Station, Saket",
    ward_name: "Saket",
    assigned_department: "PWD",
    assigned_officer_id: "officer-patel-001",
    resolved_at: null,
    resolution_note: null,
  },
  {
    id: "f3g4h5a6-b7c8-9012-cdef-333333333333",
    ticket_id: "F3G4H5A6",
    title: "No water in Rohini Sector 11 for three days, residents distressed",
    description: "Complete water supply disruption in Rohini Sector 11. Residents have been without water for 3 consecutive days.",
    status: "in_progress",
    severity: "L2",
    created_at: new Date(Date.now() - 4 * 86400000).toISOString(),
    address_text: "Block C, Rohini Sector 11",
    ward_name: "Rohini Sector 11",
    assigned_department: "DJB",
    assigned_officer_id: "officer-kumar-002",
    resolved_at: null,
    resolution_note: null,
  },
  {
    id: "g4h5i6a7-b8c9-0123-defg-444444444444",
    ticket_id: "G4H5I6A7",
    title: "Waterlogging in front of Laxmi Nagar Metro Station blocking commuter access",
    description: "Severe waterlogging after rain near Laxmi Nagar Metro gate no. 3. Commuters unable to access the station safely.",
    status: "resolved",
    severity: "L3",
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    address_text: "Gate 3, Laxmi Nagar Metro Station",
    ward_name: "Laxmi Nagar",
    assigned_department: "MCD",
    assigned_officer_id: null,
    resolved_at: new Date(Date.now() - 1 * 86400000).toISOString(),
    resolution_note: "Drain cleared and water pumped out by MCD team.",
  },
  {
    id: "h5i6j7a8-b9c0-1234-efgh-555555555555",
    ticket_id: "H5I6J7A8",
    title: "Transformer exploded in Hauz Khas right now",
    description: "A distribution transformer in Hauz Khas Enclave has exploded with visible sparking. Area is cordoned off by residents.",
    status: "resolved",
    severity: "L4",
    created_at: new Date(Date.now() - 6 * 86400000).toISOString(),
    address_text: "Hauz Khas Enclave, Block E",
    ward_name: "Hauz Khas",
    assigned_department: "BSES",
    assigned_officer_id: null,
    resolved_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    resolution_note: "Transformer replaced by BSES emergency team within 8 hours.",
  },
  {
    id: "i6j7k8a9-b0c1-2345-fghi-666666666666",
    ticket_id: "I6J7K8A9",
    title: "Smoking transformer in Janakpuri Block B posing fire and electrocution risk",
    description: "Transformer in Janakpuri Block B is emitting smoke and sparks. Residents have vacated nearby homes. Fire risk is imminent.",
    status: "resolved",
    severity: "L4",
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    address_text: "Block B, Janakpuri West",
    ward_name: "Janakpuri",
    assigned_department: "BSES",
    assigned_officer_id: null,
    resolved_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    resolution_note: "Fire services attended. Transformer isolated and replaced.",
  },
];
